### ISSUE TITLE
MariadbConnectionConfiguration.fromOptions() do not handle sessionVariables

### ISSUE THREAD

**Issue by ishi** [mariadb-corporation/mariadb-connector-r2dbc#13]
I try to connect to MariaDB and set sql_mode for the session using a connection string. Because I want to be provider independent I use factory classes to create the connection like so.
```
var connectionUrl= "r2dbc:mariadb://admin:pass@localhost:3306/dbname?sessionVariables=sql_mode='ANSI'";
var factoryOptions = ConnectionFactoryOptions.parse(connectionUrl);
var connectionFactory = ConnectionFactories.get(factoryOptions);
```

Internally `MariadbConnectionConfiguration.fromOptions(factoryOptions)` is used which do not handle sessionVariables.

**Comment by rusher** [comment]
Issue created https://jira.mariadb.org/browse/R2DBC-27.
This will be in next corrective version

**Comment by ishi** [comment]
Thanks for the quick reaction on the issue. Can we close it since the related issue has been resolved?
