### ISSUE TITLE
SSL connection to MySQL 5.7

### ISSUE THREAD

**Issue by sshark** [mariadb-corporation/mariadb-connector-r2dbc#15]
I can connect via SSL to the MySQL server using *r2dbc-mysql* using the URL r2dbc:mysql://localhost:3306/EMSV2?tlsVersion=TLSv1.2. However, switching to *r2dbc-mariadb* and using a different URL I got an exception, *Access denied for user 'dbuser'@'localhost' (using password: YES)*, from the driver though I have added the options `tlsProtocol=TLSv1.2` & `sslMode=ENABLE_TRUST` to the URL. Do I have to provide the server certification in my connection? Is there a way to make it just accept the server certificate? Thanks

**Comment by kschlesselmann** [comment]
@sshark Looks like that I've run into the same issue. What was your solution?

**Comment by sshark** [comment]
My solution is to use latest r2dbc-mysql with Spring Boot 2.4.5. Earlier, with Spring Boot 2.3.2 and perhaps 2.4.5, I ran into this problem.

**Comment by rusher** [comment]
if having that kind of error, it's probably either that user doesn't exist, doesn't hav access to schema, or needs additional things, like required client authentication (X509)
