### ISSUE TITLE
columns of type Bit(1) did not convert to Boolean

### ISSUE THREAD

**Issue by guilhermesena-hotmart** [mariadb-corporation/mariadb-connector-r2dbc#16]
The result of a type Bit(1) return a ByteSet type and show a string like { "empty": true }, i this case the return would be a boolean

**Comment by rusher** [comment]
that have been corrected with [[R2DBC-24] default conversion of Bit(1)/TINYINT(1)](https://github.com/mariadb-corporation/mariadb-connector-r2dbc/commit/389b1f0310a3d45b03142cbc795a62b8bdceeb56) to Boolean in 
1.0.2
