### ISSUE TITLE
Map TIME data type to LocalTime instead of Duration

### ISSUE THREAD

**Issue by onyn** [mariadb-corporation/mariadb-connector-r2dbc#19]
Noticed that `TIME` data type mapped to `java.time.Duration` instead of `java.time.LocalTime`.

https://github.com/mariadb-corporation/mariadb-connector-r2dbc/blob/5fab63c885dbfde4d60f709a2734fec12b0853ec/src/main/java/org/mariadb/r2dbc/codec/Codecs.java#L48

That's intentionally or mistake?

**Comment by rusher** [comment]
this will be corrected with next version (https://jira.mariadb.org/browse/R2DBC-50)
