### ISSUE TITLE
MariadbConnectionConfiguration.Builder exposes public fields

### ISSUE THREAD

**Issue by mp911de** [mariadb-corporation/mariadb-connector-r2dbc#2]
The following fields in `Builder` are `public`:

* `rsaPublicKey`
* `cachingRsaPublicKey`
* `allowPublicKeyRetrieval`

Those should be rather `private` and only be settable via configuration methods.

**Comment by rusher** [comment]
right, corrected for next version (in 0.8.1-alpha2 SNAPSHOT)
