### ISSUE TITLE
Provide a way to configure `LoopResources` from `ConnectionFactoryOption`

### ISSUE THREAD

**Issue by ks-yim** [mariadb-corporation/mariadb-connector-r2dbc#20]
#### Motivation:
* Users may want to share netty `EventLoopGroup` among multiple async libraries/framework which usually manage their own.

#### Suggested Change:
* It would be nice if `mariadb-connector-r2dbc` makes its backing `EventLoopGroup` configurable by accepting `Option<LoopResources>` or `Option<EventLoopGroup>` (Ref. https://github.com/pgjdbc/r2dbc-postgresql/blob/main/src/main/java/io/r2dbc/postgresql/PostgresqlConnectionFactoryProvider.java#L104).

**Comment by rusher** [comment]
closing since resolved with https://github.com/mariadb-corporation/mariadb-connector-r2dbc/pull/21
