### ISSUE TITLE
Upgrade to R2DBC SPI 0.9.1.RELEASE

### ISSUE THREAD

**Issue by mp911de** [mariadb-corporation/mariadb-connector-r2dbc#30]
Contains already the fix for `TestKit`.

**Comment by mp911de** [comment]
Related: When do you plan to ship `1.1.0` GA as we intended to ship the R2DBC BOM for 0.9 today (https://github.com/r2dbc/r2dbc-bom/issues/57)

**Comment by rusher** [comment]
I'm currently working on R2DBC driver. That will be in 2-3 weeks.

**Comment by gvart-sellics** [comment]
hey guys any updates on this?

**Comment by linghengqian** [comment]
I know this issue has been resolved in https://github.com/mariadb-corporation/mariadb-connector-r2dbc/releases/tag/1.1.2 . But should I still be a little curious about the plans to upgrade to R2DBC SPI 1.0.0.RELEASE ?

**Comment by rusher** [comment]
_closing since using R2DBC SPI 1.0.0.RELEASE since [1.1.3](https://jira.mariadb.org/issues/?jql=project+%3D+R2DBC+AND+fixVersion+%3D+1.1.3)_
