### ISSUE TITLE
Might have unwanted transitive dependencies through reactor-netty

### ISSUE THREAD

**Issue by jonatan-ivanov** [mariadb-corporation/mariadb-connector-r2dbc#34]
Based on [this comment](https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/issues/119#issuecomment-1212138216), since `reactor-netty` depends on all the modules in the Reactor Netty umbrella, `r2dbc-mariadb` might have dependencies that can be surprising, e.g.: `io.zipkin.brave:brave` through `reactor-netty-http-brave` or `reactor-netty-incubator-quic`, see: https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/issues/119

I don't think it is a big issue, just wanted to let you know in case you don't want certain modules there.

**Comment by rusher** [comment]
corrected in 1.2.1
