### ISSUE TITLE
SO_TIMEOUT option doesn't work

### ISSUE THREAD

**Issue by ojh3636** [mariadb-corporation/mariadb-connector-r2dbc#35]
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/15365028/186596572-9bf79baf-c841-4940-9757-39a9fb5d96d9.png">
When give the Option.of("socketTimeout") to r2dbc spi connectionFactoryOption above error occur, is there any way to fix it?

r2dbc-mariadb version is 1.0.3 (it is official version in spring boot 2.6.7)

**Comment by rusher** [comment]
closing, since it has been solved since 1.1.2
