### ISSUE TITLE
Is there support for Stored Procedures with OUT parameters?

### ISSUE THREAD

**Issue by mycroft11** [mariadb-corporation/mariadb-connector-r2dbc#42]
Is there such support, i tried following some vague examples online but i cannot get the functionality working. Any help would be greatly appreciated! :)

**Comment by rusher** [comment]
R2DBC spec has evolved since then, indicating how to deals with OUT parameters. 
You can  check some tests that use OUT parameters https://github.com/mariadb-corporation/mariadb-connector-r2dbc/blob/master/src/test/java/org/mariadb/r2dbc/integration/ProcedureResultsetTest.java
