### ISSUE TITLE
DecoderException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by YeautyYE** [mariadb-corporation/mariadb-connector-r2dbc#5]
Hello, when I use batch insert (via spring-data-r2dbc), occasionally there will be `io.netty.handler.codec.DecoderException: java.lang.NullPointerException`
Occurs at line 115 of `org.mariadb.r2dbc.client.MariadbPacketDecoder`, `state` is null
Usually when the state is `org.mariadb.r2dbc.client.DecoderState#ROW` and `cmdElement.getSink().next(msg)` on ​​line 105 is executed, `io.r2dbc.spi.R2dbcNonTransientResourceException: Connection is closing` may occur. Eventually it will call `state = null;` in `org.mariadb.r2dbc.client.MariadbPacketDecoder#connectionError()`
Causes the above NullPointerException
Does it affect the insert command and how to deal with it

**Comment by rusher** [comment]
Closing connection was not handled "synchronously" as R2DBC recommand, meaning that previous call results must be handled before closing the connection.
this was resulting in different error like "Connection is closing" or "unexpected message received when no command was send"

This is corrected in new 0.8.4-rc version with this [commit](https://github.com/mariadb-corporation/mariadb-connector-r2dbc/commit/504309ac19647ff94830ba6fb045a7fc1f8f992b)
