### ISSUE TITLE
Question: release cadence.

### ISSUE THREAD

**Issue by gm2552** [mariadb-corporation/mariadb-connector-r2dbc#55]
Is there a published release cadence for fixes?  The recent "metadata is null" merged PR is critical as the bug is holding projects back to moving to upgraded libraries (notably Spring Framework 6 and Boot 3).  A timeframe for release would be useful for planning.

Thanks

**Comment by shubha-rajan** [comment]
update on this? we're also blocked on the release of v1.14 for implementing mariadb-r2dbc support for the Google Cloud SQL Java Connector

**Comment by gm2552** [comment]
Just now getting to come back to this and see that v.1.1.4 has been released.  I have verified that the issue mentioned at the top of this thread has been resolved with the new version.  closing
