### ISSUE TITLE
Optionally disable hostname verification for SslMode.TUNNEL

### ISSUE THREAD

**Issue by shubha-rajan** [mariadb-corporation/mariadb-connector-r2dbc#56]
Hi, we're working on [supporting the MariaDB r2dbc driver in the Cloud SQL Java Connector](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/991). Cloud SQL certificates provide the instance name as the Common Name instead of a domain, which means that verifying hostnames will fail. Some examples:

- https://stackoverflow.com/questions/72214865/set-up-google-cloud-certificates-for-postgresql-database-hostname-mismatch
- https://stackoverflow.com/questions/61334993/cannot-tls-connect-to-gcp-cloud-sqlmysql-using-python3
- https://stackoverflow.com/questions/33878356/certificate-validation-on-cloud-sql

Currently, the MariaDB driver forces hostname verification when using SslMode.TUNNEL. I have a patch pull request in which I added the option to disable host verification for SSL Tunneling which I will link here.

**Comment by rusher** [comment]
closing this since merged in 1.2.0
