### ISSUE TITLE
Assignment operator not working 

### ISSUE THREAD

**Issue by sumitsum** [mariadb-corporation/mariadb-connector-r2dbc#58]
The following sql statement fails : 
```
SELECT @amount := 10;
```

Error seen:
`java.lang.IllegalStateException: Parameter at position 0 is not set`

**Comment by rusher** [comment]
`:=` doesn't exist in MySQL/MariaDB, so there will be an error... but error is not right. 
https://jira.mariadb.org/browse/R2DBC-79 created to handle that

**Comment by Stenerson** [comment]
@rusher, I've used `:=` for quite some time on complex update and select statements in MariaDB. It's also in their KB: https://mariadb.com/kb/en/assignment-operator/ 

Is there somewhere that points to this being invalid syntax in MariaDB?

**Comment by sumitsum** [comment]
@rusher MariaDB GitHub page claims that it can support MySQL as well, so I have been using it for MySQL DB as well. On MySQL DB the assignment operator works fine when run via console but fails when run via the driver.

**Comment by rusher** [comment]
yes, sorry, this is clearly a parser error that will be corrected soon. (I've initially mentionned that it was a wrong syntax and immediatly removed that part)

**Comment by sumitsum** [comment]
Thanks a lot @rusher . Will be waiting for the fix :)

**Comment by Stenerson** [comment]
Thanks @rusher! Your edit was too fast for me! 😉
