### ISSUE TITLE
Can not configure allowPublicKeyRetrieval via Options

### ISSUE THREAD

**Issue by m-kay** [mariadb-corporation/mariadb-connector-r2dbc#59]
Im trying to configure allowPublicKeyRetrieval=true via options in version 1.1.3 but this does not seem to work.

When creating the `ConnectionFactory` with
```kotlin
val options = ConnectionFactoryOptions.builder()
    .option(ConnectionFactoryOptions.DRIVER, "mariadb")
    .option(ConnectionFactoryOptions.HOST, "localhost")
    .option(ConnectionFactoryOptions.PORT, 63426)
    .option(ConnectionFactoryOptions.DATABASE, "my_database")
    .option(ConnectionFactoryOptions.USER, "test")
    .option(ConnectionFactoryOptions.PASSWORD, "password")
    .option(Option.valueOf("allowPublicKeyRetrieval"), true)
    .build()
val connectionFactory = ConnectionFactories.find(options)
println(connectionFactory.toString())
```
the following configuration is printed where `allowPublicKeyRetrieval` is not set correctly.

MariadbConnectionFactory{configuration=MariadbConnectionConfiguration{database='LOANS_SERVICE', hosts={[localhost:63426]}, connectTimeout=PT10S, tcpKeepAlive=false, tcpAbortiveClose=false, transactionReplay=false, password=*, prepareCacheSize=250, socket='null', username='test', allowMultiQueries=false, allowPipelining=true, connectionAttributes=null, sessionVariables=null, sslConfig=SslConfig{sslMode=DISABLE, serverSslCert=null, clientSslCert=null, tlsProtocol=null, clientSslKey=null}, rsaPublicKey='null', cachingRsaPublicKey='null', **allowPublicKeyRetrieval=false**, isolationLevel=null, useServerPrepStmts=false, autocommit=true, tinyInt1isBit=true, pamOtherPwd=, restrictedAuth=null}}

It seems that this option is not taken into account in [MariadbConnectionConfiguration::fromOptions](https://github.com/mariadb-corporation/mariadb-connector-r2dbc/blob/master/src/main/java/org/mariadb/r2dbc/MariadbConnectionConfiguration.java#L167)

**Comment by rusher** [comment]
will be corrected in 1.1.4
