### ISSUE TITLE
LEAK

### ISSUE THREAD

**Issue by YeautyYE** [mariadb-corporation/mariadb-connector-r2dbc#6]
I don't know whether spring-R2DBC caused or mariada-connector caused it

```
ERROR [reactor-tcp-nio-4] io.netty.util.ResourceLeakDetector[320] -| LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:363)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:139)
	io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.lang.Thread.run(Thread.java:745)
```

**Comment by rusher** [comment]
ok, first can you tell the version of the driver. 
And any hint of the code which cause this ?

**Comment by YeautyYE** [comment]
version is 0.8.4-rc

By adding the parameter `-Dio.netty.leakDetectionLevel=paranoid`, I saw that most of the memory allocation is in line 83 of `org.mariadb.r2dbc.client.MariadbPacketDecoder` ,`ByteBuf packet = buf.readRetainedSlice(4 + length);`.
I guess it may be that the next method is too slow, resulting in the failure to execute `packet.release();`. 
Thus, the excessive memory is not released.

**Comment by rusher** [comment]
This is the part where driver get socket buffer, so, most of the buffers are created there.
Issue cannot be in that part of this code, buffer cannot be garbage collected since object is referenced until release. 

There can be only 2 others part of the code where buffer are created (rows and blobs), I'll check this, even if there is already tests to avoid that normally

**Comment by YeautyYE** [comment]
ok, thanks

**Comment by rusher** [comment]
closing, since all retained buffer are now ensure to be released in new version
