### ISSUE TITLE
About releases and maintenance 

### ISSUE THREAD

**Issue by jordillachmrf** [mariadb-corporation/mariadb-connector-r2dbc#63]
r2dbc-mariadb-1.1.2 relies in r2dbc-spi-0.9.x spec and r2dbc-mariadb-1.1.3 in r2dbc-spi-1.0.x, fixes are only applied to master, that means that all the apps stuck with r2dbc-spi-0.9.x (spring-boot-2.7.x) can not benefit from bug fixing.
Any chance to review the development/maintenance flow ?

Thanks

**Comment by rusher** [comment]
There is no plan to maintain r2dbc-spi-0.9.x supported version.
