### ISSUE TITLE
Cannot set comma separated multiple value for 'sql_mode' with sessionVariable

### ISSUE THREAD

**Issue by koyapei** [mariadb-corporation/mariadb-connector-r2dbc#64]
Hi, I would like to set comma separated multiple value for `sql_mode` with sessionVariable.
But when I set `sql_mode=TRADITIONAL,NO_AUTO_VALUE_ON_ZERO,ONLY_FULL_GROUP_BY` as sessionVariable, it's parsed to `sessionVariables={NO_AUTO_VALUE_ON_ZERO=, sql_mode='TRADITIONAL, ONLY_FULL_GROUP_BY'=}`.

It seems that [`MariadbConnectionConfiguration.getMapFromString`](https://github.com/mariadb-corporation/mariadb-connector-r2dbc/blob/1.1.4/src/main/java/org/mariadb/r2dbc/MariadbConnectionConfiguration.java#L376) does not matched to this case.
Is there any workaround?

**Comment by rusher** [comment]
there isn't actually, but correction will be in next version
