### ISSUE TITLE
r2dbc-mariadb seems don't support serverTimezone or serverZoneId

### ISSUE THREAD

**Issue by patientCat** [mariadb-corporation/mariadb-connector-r2dbc#69]
when i have a table which has some fields like timestamp. how do i use r2dbc to connect mariadb with serverTimeZone or serverZoneId.
In JDBC , the option serverTimeZone was supported.
In R2dbc-Mysql , the option serverZoneId was supported.
But R2dbc-mariadb seems don't support both. 
Can someone help me?

**Comment by rusher** [comment]
done with the newly released 1.2.0 version. see `timezone` option
