### ISSUE TITLE
MariaDB server reports large amount of aborted connection warnings

### ISSUE THREAD

**Issue by mdeso** [mariadb-corporation/mariadb-connector-r2dbc#73]
We noticed a large amount (several 100K per day) of warnings like the following on our server:

> `[Warning] Aborted connection <n> to db: '<dbname>' user: '<user>' host: '<host-ip>' (Got an error reading communication packets)`

I could reproduce this with a locally running MariaDB server and trace it back to the mariadb-connector-r2dbc (originally version 1.1.2, but I also tried 1.1.4). The driver being present without database access already causes a warning every 60 seconds. Accessing the database seems to cause a warning for each access. From the description it may be related to/caused by #32. It seems as if connections are not closed correctly, causing the server to perform cleanup the open connections.

I was able to fix this behavior by using the MySQL R2DBC driver `io.asyncer:r2dbc-mysql:1.0.4` instead. Although it doesn't officially support MariaDB it seems to work fine and doesn't produce these connections warnings.

#51 seems to describe the same problem but the proposed solution (update mariadb-java-connector to 3.0.9) makes no sense as we only use r2dbc.

**Comment by rusher** [comment]
Release in 1.2.0
