### ISSUE TITLE
MariaDB driver disables logging in spring-boot application

### ISSUE THREAD

**Issue by mindhaq** [mariadb-corporation/mariadb-connector-r2dbc#9]
A basic spring-boot application using the mariaDB r2dbc connector is not logging as it should. It looks like any logback-spring.xml files are being ignored.

Output during startup:

```
> Task :bootRun

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v2.4.0-SNAPSHOT)

2020-11-10 | 00:57:20.833 | background-preinit   |  WARN | o.s.h.c.j.Jackson2ObjectMapperBuilder | For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
```

Demo repository:

https://github.com/mindhaq/spring-boot-bugreport-24102/tree/mariadb

Related issue in spring-boot:

https://github.com/spring-projects/spring-boot/issues/24102

**Comment by mindhaq** [comment]
As mentioned by @snicoll at spring-boot, there is a "`logback-test.xml` at the root of the classpath that [takes precedence over any other configuration files](http://logback.qos.ch/manual/configuration.html)."

**Comment by rusher** [comment]
0.8.4 release did contain files benchmark profile (benchmark source contain this logback-test.xml that disable logging to avoid having wrong benchmark comparison).
The next version (this week) will contain corrections to avoid that.

**Comment by rusher** [comment]
latest version correct that behaviour, so closing issue
